### ISSUE TITLE
allow to read input from stdin

### ISSUE THREAD

**Issue by zacchiro** [beancount/beancount2ledger#13]
As per title.

Weirdly enough, currently beancount2ledger accepts "-" as an argument, without failing, but it does nothing:
```
$ beancount2ledger - < current.beancount

$

$ beancount2ledger < current.beancount 
usage: beancount2ledger [-h] [-f {ledger,hledger}] [-V] file
beancount2ledger: error: the following arguments are required: file
$

$ beancount2ledger current.beancount 
# this works as expected
```

**Comment by tbm** [comment]
Thanks. Yes, I noticed that as well.  I haven't had the time to investigate yet.

You mention clicks rather than argparse on IRC.  Maybe switching will fix that.

**Comment by zacchiro** [comment]
if you go for [click](https://click.palletsprojects.com/en/7.x/), a [file argument](https://click.palletsprojects.com/en/7.x/arguments/#file-arguments) will indeed support this out of the box

**Comment by tbm** [comment]
Actually, I think it's something I did rather than argparse.

**Comment by dnicolodi** [comment]
Most probably the problem arises here https://github.com/beancount/beancount2ledger/blob/master/beancount2ledger/cli.py#L46 because stdin probably does not have a valid name. Please note that, with the recent work on the beancount parser, the parser should be able to operate on Python file objects. This should simplify the code a bit, as you can simply write:
```py
print(beancount2ledger.convert_file(args.file, args.format))
```
without having to fetch the name of the file object. In this case the file should be opened in binary mode, ie `rb` instead of `r`. I haven't tested if the loader does the right thing if gets a file object and not a file name. Please let me know if you encounter any problems.

**Comment by tbm** [comment]
@dnicolodi the reason I'm using the filename instead of the file object is because I got:

```
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper
```

with 'rb' I get:

```
TypeError: expected str, bytes or os.PathLike object, not _io.BufferedReader
```

**Comment by tbm** [comment]
So `load_file()` definitely expects a filename (on the v2 branch):

```
    loader.load_file(input)
  File "/home/tbm/.local/lib/python3.7/site-packages/beancount/loader.py", line 78, in load_file
    filename = path.expandvars(path.expanduser(filename))
  File "/usr/lib/python3.7/posixpath.py", line 235, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not _io.BufferedReader
```

**Comment by dnicolodi** [comment]
I had a quick look and indeed the machinery in `beancount.loader` wants a file path. For this reason it also cannot work on stdin. Adapting it to accept a file object seems possible but quite some work. That code definitely would benefit from some cleanup...

**Comment by dnicolodi** [comment]
Judging from some other bugs I am not sure you actually want to operate on the "cooked" output of `beancount.loader`, maybe operating on the output of the parser (before the booking has taken place) would be a better way to translate the input file avoiding any transformation implemented in beancount. For example, I think operating on the parser output rather than on the loader output is the only way to solve issue #10.

**Comment by tbm** [comment]
> For example, I think operating on the parser output rather than on the loader output is the only way to solve issue #10.

Actually, I can solve this by looking for `posting.meta['__automatic__']`, but using the parser output might be useful for other thing.  I will look into that. Thank you!
